### Get all notes

GET http://localhost:3001/api/blogs


### Create a note

POST http://localhost:3001/api/blogs
content-type: application/json

{
  "title": "Test posting from VS REST Client",
  "author": "Tester",
  "url": "test/vs-code.com",
  "likes": 1
}


### Create a note without likes

POST http://localhost:3001/api/blogs
content-type: application/json

{
  "title": "Test posting from VS REST Client",
  "author": "Tester",
  "url": "test/vs-code.com"
}

